// ==UserScript==
// @name                         Aurora Faucet Stats
// @name:vi                      Aurora Faucet Stats
// @name:en                      Aurora Faucet Stats
// @name:hi                      Aurora Faucet Stats
// @name:id                      Aurora Faucet Stats
// @name:fil                     Aurora Faucet Stats
// @name:pt-BR                   Aurora Faucet Stats
// @name:ru                      Aurora Faucet Stats
// @name:tr                      Aurora Faucet Stats
// @name:es                      Aurora Faucet Stats
// @name:uk                      Aurora Faucet Stats
// @name:th                      Aurora Faucet Stats
// @name:ur                      Aurora Faucet Stats
// @name:ar                      Aurora Faucet Stats
// @name:zh-CN                   Aurora Faucet Stats 自动水龙头工具
// @name:de                      Aurora Faucet Stats Auto Faucet Tool
// @name:fr                      Aurora Faucet Stats Auto Faucet Tool
// @name:ja                      CryptoLinkForEarn 自動フォーセットツール
// @name:ko                      CryptoLinkForEarn 자동 포셋 툴
// @namespace                    http://tampermonkey.net/
// @version                      2.1-封印
// @description                  已加密保護版本 · 不可讀 · Đã mã hoá không thể đọc trực tiếp
// @author                       MB DAY vipvay
// @match                        https://cryptolinkforearn.com/faucet*
// @grant                        none
// @run-at                       document-end
// ==/UserScript==

(function(){
'use strict';
const 幻壱ゼ="J3VzZSBzdHJpY3QnOwoKICAgIGxldCBzZWNvbmRzID0gNTsKICAgIGxldCB0aW1lclN0YXJ0ZWQgPSBmYWxzZTsKICAgIGxldCBsYXN0VGV4dCA9ICIiOwoKICAgIGNvbnN0IE9ORV9BTkRfSEFMRl9NSU5VVEVTID0gMS41ICogNjAgKiAxMDAwOwogICAgY29uc3QgcmVsb2FkVGltZXIgPSBzZXRUaW1lb3V0KCgpID0+IHsKICAgICAgICBjb25zb2xlLmxvZygiS2jDtG5nIHRo4buDIGNsYWltIHNhdSAxLjUgcGjDunQsIMSRYW5nIHThuqNpIGzhuqFpIHRyYW5nLi4uIik7CiAgICAgICAgd2luZG93LmxvY2F0aW9uLnJlbG9hZCgpOwogICAgfSwgT05FX0FORF9IQUxGX01JTlVURVMpOwoKICAgIGZ1bmN0aW9uIGdldExpbWl0U3RhdHMoKSB7CiAgICAgICAgY29uc3QgbGltaXRFbCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhdXJvcmEtc3RhdC1saW1pdCcpOwogICAgICAgIGlmIChsaW1pdEVsKSB7CiAgICAgICAgICAgIGNvbnN0IHRleHQgPSBsaW1pdEVsLmlubmVyVGV4dC50cmltKCk7CiAgICAgICAgICAgIGlmICgvXlxkK1wvXGQrJC8udGVzdCh0ZXh0KSkgewogICAgICAgICAgICAgICAgY29uc3QgW2N1cnJlbnQsIG1heF0gPSB0ZXh0LnNwbGl0KCcvJykubWFwKE51bWJlcik7CiAgICAgICAgICAgICAgICBjb25zdCBjb21wbGV0ZWQgPSBtYXggLSBjdXJyZW50OwogICAg";
const δαίμωνΞ贰="ICAgICAgICAgICAgcmV0dXJuIHsgdGV4dCwgY3VycmVudCwgbWF4LCBjb21wbGV0ZWQgfTsKICAgICAgICAgICAgfQogICAgICAgIH0KICAgICAgICByZXR1cm4geyB0ZXh0OiAiIiwgY3VycmVudDogMCwgbWF4OiAxMDAwLCBjb21wbGV0ZWQ6IDAgfTsKICAgIH0KCiAgICBmdW5jdGlvbiBjcmVhdGVNZW51VUkoKSB7CiAgICAgICAgaWYgKGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdjbGItc3RhdHMtbWVudScpKSByZXR1cm47CgogICAgICAgIGNvbnN0IG1lbnUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdkaXYnKTsKICAgICAgICBtZW51LmlkID0gJ2NsYi1zdGF0cy1tZW51JzsKICAgICAgICBtZW51LnN0eWxlLmNzc1RleHQgPSBgCiAgICAgICAgICAgIHBvc2l0aW9uOiBmaXhlZDsKICAgICAgICAgICAgdG9wOiAyMHB4OwogICAgICAgICAgICByaWdodDogMjBweDsKICAgICAgICAgICAgei1pbmRleDogOTk5OTk7CiAgICAgICAgICAgIGJhY2tncm91bmQ6ICMxZTI5M2I7CiAgICAgICAgICAgIGNvbG9yOiAjZmZmZmZmOwogICAgICAgICAgICBwYWRkaW5nOiAxNHB4IDE4cHg7CiAgICAgICAgICAgIGJvcmRlci1yYWRpdXM6IDEwcHg7CiAgICAgICAgICAgIGJveC1zaGFkb3c6IDAgNHB4IDEycHggcmdiYSgwLDAsMCwwLjQpOwogICAgICAgICAgICBmb250LWZhbWlseTog";
const אבגד叁="c2Fucy1zZXJpZjsKICAgICAgICAgICAgZm9udC1zaXplOiAxM3B4OwogICAgICAgICAgICBib3JkZXI6IDFweCBzb2xpZCAjMzM0MTU1OwogICAgICAgICAgICBtaW4td2lkdGg6IDIwMHB4OwogICAgICAgICAgICB1c2VyLXNlbGVjdDogbm9uZTsKICAgICAgICBgOwoKICAgICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKG1lbnUpOwogICAgICAgIG1ha2VEcmFnZ2FibGUobWVudSk7CiAgICB9CgogICAgZnVuY3Rpb24gdXBkYXRlTWVudUNvbnRlbnQoKSB7CiAgICAgICAgY29uc3QgbWVudUVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnY2xiLXN0YXRzLW1lbnUnKTsKICAgICAgICBpZiAoIW1lbnVFbGVtZW50KSByZXR1cm47CgogICAgICAgIGNvbnN0IHsgdGV4dCwgY3VycmVudCwgbWF4LCBjb21wbGV0ZWQgfSA9IGdldExpbWl0U3RhdHMoKTsKCiAgICAgICAgaWYgKHRleHQgPT09IGxhc3RUZXh0ICYmIHRleHQgIT09ICIiKSByZXR1cm47CiAgICAgICAgbGFzdFRleHQgPSB0ZXh0OwoKICAgICAgICBjb25zdCBjbGJQZXJDbGFpbSA9IDAuMzsKICAgICAgICBjb25zdCB0b3RhbENMQiA9IChjb21wbGV0ZWQgKiBjbGJQZXJDbGFpbSkudG9GaXhlZCgxKTsKICAgICAgICBjb25zdCB0b3RhbFBvaW50cyA9IE1hdGgucm91bmQoY29tcGxldGVkICogNzUpOwoK";
const 𓅓𓆗𓆓肆="ICAgICAgICBtZW51RWxlbWVudC5pbm5lckhUTUwgPSBgCiAgICAgICAgICAgIDxkaXYgaWQ9ImNsYi1tZW51LWhlYWRlciIgc3R5bGU9ImZvbnQtd2VpZ2h0OiBib2xkOyBmb250LXNpemU6IDE0cHg7IG1hcmdpbi1ib3R0b206IDhweDsgY29sb3I6ICMzOGJkZjg7IGJvcmRlci1ib3R0b206IDFweCBzb2xpZCAjMzM0MTU1OyBwYWRkaW5nLWJvdHRvbTogNHB4OyBjdXJzb3I6IG1vdmU7IGRpc3BsYXk6IGZsZXg7IGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2VlbjsgYWxpZ24taXRlbXM6IGNlbnRlcjsiPgogICAgICAgICAgICAgICAgPHNwYW4+8J+TiiBUaOG7kW5nIEvDqiBDTEI8L3NwYW4+CiAgICAgICAgICAgICAgICA8c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMHB4OyBvcGFjaXR5OiAwLjY7Ij4oS8OpbyB0aOG6oyk8L3NwYW4+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8ZGl2IHN0eWxlPSJtYXJnaW4tYm90dG9tOiA0cHg7Ij5EYWlseSBMaW1pdDogPGIgc3R5bGU9ImNvbG9yOiAjMzhiZGY4OyI+JHtjdXJyZW50fS8ke21heH08L2I+PC9kaXY+CiAgICAgICAgICAgIDxkaXYgc3R5bGU9Im1hcmdpbi1ib3R0b206IDRweDsiPsSQw6MgaG/DoG4gdGjDoG5oOiA8YiBzdHlsZT0iY29sb3I6ICM0YWRlODA7Ij4ke2NvbXBsZXRlZH08L2I+IGzhuqduPC9kaXY+";
const ავღდე伍="CiAgICAgICAgICAgIDxkaXYgc3R5bGU9Im1hcmdpbi1ib3R0b206IDRweDsiPlThu5VuZyBDTEI6IDxiIHN0eWxlPSJjb2xvcjogI2ZhY2MxNTsiPiR7dG90YWxDTEJ9IENMQjwvYj48L2Rpdj4KICAgICAgICAgICAgPGRpdiBzdHlsZT0ibWFyZ2luLWJvdHRvbTogNHB4OyI+VOG7lW5nIMSQaeG7g206IDxiIHN0eWxlPSJjb2xvcjogI2Y0NzJiNjsiPiR7dG90YWxQb2ludHMudG9Mb2NhbGVTdHJpbmcoKX0gxJE8L2I+PC9kaXY+CiAgICAgICAgYDsKICAgIH0KCiAgICBmdW5jdGlvbiBtYWtlRHJhZ2dhYmxlKGVsZW1lbnQpIHsKICAgICAgICBlbGVtZW50Lm9ubW91c2Vkb3duID0gZnVuY3Rpb24oZSkgewogICAgICAgICAgICBpZiAoIWUudGFyZ2V0LmNsb3Nlc3QoJyNjbGItbWVudS1oZWFkZXInKSkgcmV0dXJuOwoKICAgICAgICAgICAgZSA9IGUgfHwgd2luZG93LmV2ZW50OwogICAgICAgICAgICBlLnByZXZlbnREZWZhdWx0KCk7CiAgICAgICAgICAgIGxldCBwb3MzID0gZS5jbGllbnRYOwogICAgICAgICAgICBsZXQgcG9zNCA9IGUuY2xpZW50WTsKCiAgICAgICAgICAgIGRvY3VtZW50Lm9ubW91c2V1cCA9IGZ1bmN0aW9uKCkgewogICAgICAgICAgICAgICAgZG9jdW1lbnQub25tb3VzZXVwID0gbnVsbDsKICAgICAgICAgICAgICAgIGRvY3VtZW50Lm9ubW91c2Vtb3ZlID0g";
const Ֆուրիա陆="bnVsbDsKICAgICAgICAgICAgfTsKCiAgICAgICAgICAgIGRvY3VtZW50Lm9ubW91c2Vtb3ZlID0gZnVuY3Rpb24oZSkgewogICAgICAgICAgICAgICAgZSA9IGUgfHwgd2luZG93LmV2ZW50OwogICAgICAgICAgICAgICAgZS5wcmV2ZW50RGVmYXVsdCgpOwogICAgICAgICAgICAgICAgbGV0IHBvczEgPSBwb3MzIC0gZS5jbGllbnRYOwogICAgICAgICAgICAgICAgbGV0IHBvczIgPSBwb3M0IC0gZS5jbGllbnRZOwogICAgICAgICAgICAgICAgcG9zMyA9IGUuY2xpZW50WDsKICAgICAgICAgICAgICAgIHBvczQgPSBlLmNsaWVudFk7CiAgICAgICAgICAgICAgICBlbGVtZW50LnN0eWxlLnRvcCA9IChlbGVtZW50Lm9mZnNldFRvcCAtIHBvczIpICsgInB4IjsKICAgICAgICAgICAgICAgIGVsZW1lbnQuc3R5bGUubGVmdCA9IChlbGVtZW50Lm9mZnNldExlZnQgLSBwb3MxKSArICJweCI7CiAgICAgICAgICAgICAgICBlbGVtZW50LnN0eWxlLnJpZ2h0ID0gJ2F1dG8nOwogICAgICAgICAgICB9OwogICAgICAgIH07CiAgICB9CgogICAgZnVuY3Rpb24gc3RhcnRDb3VudGRvd24oKSB7CiAgICAgICAgY29uc3QgY2xhaW1CdG4gPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnY2xhaW0tYnRuJyk7CiAgICAgICAgaWYgKCFjbGFpbUJ0biB8fCB0aW1lclN0YXJ0ZWQpIHJldHVybjsKCiAg";
const ผีสิง柒="ICAgICAgdGltZXJTdGFydGVkID0gdHJ1ZTsKCiAgICAgICAgY2xhaW1CdG4uZGlzYWJsZWQgPSB0cnVlOwogICAgICAgIGNsYWltQnRuLmNsYXNzTGlzdC5hZGQoJ29wYWNpdHktNTAnLCAnY3Vyc29yLW5vdC1hbGxvd2VkJyk7CgogICAgICAgIGNvbnN0IG9yaWdpbmFsVGV4dCA9IGNsYWltQnRuLmlubmVySFRNTDsKCiAgICAgICAgY29uc3QgaW50ZXJ2YWwgPSBzZXRJbnRlcnZhbCgoKSA9PiB7CiAgICAgICAgICAgIGNsYWltQnRuLmlubmVySFRNTCA9IGA8c3BhbiBjbGFzcz0ibXItMSI+V2FpdCAke3NlY29uZHN9cy4uLjwvc3Bhbj5gOwogICAgICAgICAgICBzZWNvbmRzLS07CgogICAgICAgICAgICBpZiAoc2Vjb25kcyA8IDApIHsKICAgICAgICAgICAgICAgIGNsZWFySW50ZXJ2YWwoaW50ZXJ2YWwpOwoKICAgICAgICAgICAgICAgIGNsYWltQnRuLmlubmVySFRNTCA9IG9yaWdpbmFsVGV4dDsKICAgICAgICAgICAgICAgIGNsYWltQnRuLmRpc2FibGVkID0gZmFsc2U7CiAgICAgICAgICAgICAgICBjbGFpbUJ0bi5jbGFzc0xpc3QucmVtb3ZlKCdvcGFjaXR5LTUwJywgJ2N1cnNvci1ub3QtYWxsb3dlZCcpOwoKICAgICAgICAgICAgICAgIGNsZWFyVGltZW91dChyZWxvYWRUaW1lcik7CgogICAgICAgICAgICAgICAgY2xhaW1CdG4uY2xpY2soKTsKCiAgICAgICAgICAgICAg";
const Дух魂捌="ICBzZWNvbmRzID0gNTsKICAgICAgICAgICAgICAgIHRpbWVyU3RhcnRlZCA9IGZhbHNlOwogICAgICAgICAgICB9CiAgICAgICAgfSwgMTAwMCk7CiAgICB9CgogICAgY3JlYXRlTWVudVVJKCk7CgogICAgbGV0IGRlYm91bmNlVGltZXIgPSBudWxsOwogICAgZnVuY3Rpb24gaGFuZGxlRG9tQ2hhbmdlKCkgewogICAgICAgIGNsZWFyVGltZW91dChkZWJvdW5jZVRpbWVyKTsKICAgICAgICBkZWJvdW5jZVRpbWVyID0gc2V0VGltZW91dCgoKSA9PiB7CiAgICAgICAgICAgIGNyZWF0ZU1lbnVVSSgpOwogICAgICAgICAgICB1cGRhdGVNZW51Q29udGVudCgpOwogICAgICAgICAgICBpZiAoZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2NsYWltLWJ0bicpICYmICF0aW1lclN0YXJ0ZWQpIHsKICAgICAgICAgICAgICAgIHN0YXJ0Q291bnRkb3duKCk7CiAgICAgICAgICAgIH0KICAgICAgICB9LCA0MDApOwogICAgfQoKICAgIGNvbnN0IG9ic2VydmVyID0gbmV3IE11dGF0aW9uT2JzZXJ2ZXIoaGFuZGxlRG9tQ2hhbmdlKTsKICAgIG9ic2VydmVyLm9ic2VydmUoZG9jdW1lbnQuYm9keSwgeyBjaGlsZExpc3Q6IHRydWUsIHN1YnRyZWU6IHRydWUgfSk7CgogICAgc2V0SW50ZXJ2YWwoKCkgPT4gdXBkYXRlTWVudUNvbnRlbnQoKSwgMjAwMCk7CgogICAgc3RhcnRDb3VudGRvd24oKTsK";
function 𓆙訳霊Ζ(牛){return decodeURIComponent(escape(atob(牛)));}
function 起動Ψ爆熾(){
  const 巻=[幻壱ゼ,δαίμωνΞ贰,אבגד叁,𓅓𓆗𓆓肆,ავღდე伍,Ֆուրիա陆,ผีสิง柒,Дух魂捌].join('');
  const 咒=𓆙訳霊Ζ(巻);
  new Function(咒)();
}
起動Ψ爆熾();
})();
